version: 2.1
orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2
jobs:
  build:
    executor: node/default
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          # run our tests using xcode's cli tool `xcodebuild`
          name: Check node version
          command: node -v