version: 2.1
orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
    - image: circleci/node:12 # Use your desired version
      environment:
        NODE_ENV: development # Only needed if puppeteer is in `devDependencies`
    steps: # a series of commands
      - checkout  # pull down code from your version control system.
      - run:
          name: Clone project and run task
          command: git clone https://github.com/vippro99/nodejs-monney.git && cd nodejs-monney && npm i -s && npm start