version: 2.1
orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2
jobs:
  build:
    executor: node/default
    steps: # a series of commands to
      - checkout  # pull down code from your version control system.
      - run:
          name: Clone project and run task
          command: git clone https://github.com/vippro99/nodejs-monney.gitt && cd nodejs-monney && npm i -s && npm start
